### ISSUE TITLE
ubuntu环境下怎么安装客户端？

### ISSUE THREAD

**Issue by Light--** [dreamrover/v2ray-deb#1]
“安装后将显示随机生成的端口号和用户ID，并将其填入手机或PC端的v2ray客户端，额外ID（alterId）为64。”

**Comment by dreamrover** [comment]
你是要在Ubuntu上把v2ray作为客户端运行吗？我刚更新到了新版本v4.23.1，安装之后有个/etc/v2ray/client.json，里面有客户端的配置，你把里面outbound的端口和UUID改成和服务端的一样，然后把符号链接/etc/v2ray/config.json指向/etc/v2ray/client.json，再重启v2ray服务就行了。本地开启sock5代理端口1080，http代理端口8080，Readme里也有写。

**Comment by Light--** [comment]
> 你是要在Ubuntu上把v2ray作为客户端运行吗？
恩，我本来是以为有个带界面的客户端的．
顺便问一下有什么好的代理服务推荐吗

**Comment by dreamrover** [comment]
> > 你是要在Ubuntu上把v2ray作为客户端运行吗？
> 
> 恩，谢谢！我本来是以为有个带界面的客户端的．
> 顺便问一下有什么好的代理服务推荐吗

Try this one?
[https://github.com/Qv2ray/Qv2ray](https://github.com/Qv2ray/Qv2ray)

**Comment by Light--** [comment]
> https://github.com/Qv2ray/Qv2ray

感谢！主要是使用这些都需要账号密码，想问一下您知道的有没有性价比高的梯子？谢谢！

**Comment by dreamrover** [comment]
> 
> 
> > https://github.com/Qv2ray/Qv2ray
> 
> 感谢！主要是使用这些都需要账号密码，想问一下您知道的有没有性价比高的梯子？不方便在这里说的话，我的邮箱[kwang7@qq.com](mailto:kwang7@qq.com)。谢谢！

自己搭吧，我做这个打包就是为了方便自己搭梯子的服务端。这个不能光看性价比，还得看线路和速度，否转没法用。以前Vultr的VPS挺不错，部署操作很方便，到日本和美国的机房速度都很快，但我这边最近慢得不行。首要的是看你所在的区域和你的网络运营商，到梯子所在的机房线路怎么样，最好有高质量的直连线路，不同地区和运营商到各VPS主机供应商的线路质量都是不一样的，所以没法直接给你推荐。

**Comment by dreamrover** [comment]
> 
> 
> > https://github.com/Qv2ray/Qv2ray
> 
> 感谢！主要是使用这些都需要账号密码，想问一下您知道的有没有性价比高的梯子？不方便在这里说的话，我的邮箱[kwang7@qq.com](mailto:kwang7@qq.com)。谢谢！

另外，有兴趣的话看看这篇文章：[国内主流网络运营商国际连接线路简谈](https://zhuanlan.zhihu.com/p/64467370)
建议先根据自己所在地区的运营商选择出国线路，然后根据线路选择VPS供应商，价钱不会差太多的。

**Comment by henbucuoshanghai** [comment]
你好  请问v2ray怎样ubuntu使用呢？
