### ISSUE TITLE
更新时老的配置文件会被覆盖掉

### ISSUE THREAD

**Issue by dianlujitao** [dreamrover/v2ray-deb#2]
RT，每次更新都会重新随机生成配置json并覆盖当前的。
arch用户对deb不熟，似乎可以通过添加conffiles把他们whitelist掉 https://manpages.debian.org/testing/dpkg-dev/deb-conffiles.5.en.html

**Comment by dreamrover** [comment]
很好的建议，我之前也考虑过，等有空加进去~

**Comment by dreamrover** [comment]
conffiles已加入，下个版本打包进deb

**Comment by dreamrover** [comment]
4.25.1版已加入此功能。
