### ISSUE TITLE
about debian packaging

### ISSUE THREAD

**Issue by rogers0** [dreamrover/v2ray-deb#4]
> 作为服务端时无法配置为同时监听多个端口

Please kindly report what's the problem. For example, provide config and log.

The build script for debian package is on salsa:
- https://salsa.debian.org/go-team/packages/golang-v2ray-core/-/blob/debian/sid/debian/rules

Maybe you can patch it, if there's anything missing?
Thank you!

> v2ray尚未进入Ubuntu官方源

It hit ubuntu archive already:
- https://launchpad.net/ubuntu/+source/golang-v2ray-core

**Comment by grandpaul** [comment]
Hi all.

I think that is fixed after 2020 Oct 10th in Debian unstable and testing.

For "作為服務端時無法配置為同時監聽多個端口"
The main reason is when you Debianized v2ray, according to the FHS and Debian policy, you should not install data files like "geoip.dat" to /usr/bin. 

In Debian, those files are installed to /etc/v2ray. So you have to set the environment variable "export V2RAY_LOCATION_ASSET=/etc/v2ray" before running any v2ray commands.

I've tried your sever.json. Execute "V2RAY_LOCATION_ASSET=/etc/v2ray v2ray -c server.json" and it  did listen to several ports without problems.
